# Generated by Django 4.2.8 on 2026-01-06 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("alternatives", models.JSONField(default=list)),
                (
                    "scale_type",
                    models.IntegerField(
                        choices=[
                            (1, "Integer"),
                            (2, "Balanced"),
                            (3, "Power"),
                            (4, "Ma-Zheng"),
                            (5, "Donegan"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("input", "Input Alternatives"),
                            ("comparison", "Making Comparisons"),
                            ("completed", "Completed"),
                        ],
                        default="input",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matrix", models.JSONField()),
                ("weights", models.JSONField()),
                ("rankings", models.JSONField()),
                ("lambda_max", models.FloatField()),
                ("consistency_index", models.FloatField()),
                ("consistency_ratio", models.FloatField()),
                ("is_consistent", models.BooleanField()),
                ("recommendations", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="comparisons.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index_a", models.IntegerField()),
                ("index_b", models.IntegerField()),
                ("value", models.FloatField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("more", "More"), ("less", "Less")], max_length=10
                    ),
                ),
                ("reliability", models.FloatField(default=0.0)),
                ("scale_str", models.CharField(default="259", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="comparisons.project",
                    ),
                ),
            ],
            options={
                "ordering": ["index_a", "index_b"],
                "unique_together": {("project", "index_a", "index_b")},
            },
        ),
    ]
