# Generated by Django 4.2.8 on 2026-01-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comparisons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparison",
            name="gradations",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="comparison",
            name="refinement_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comparison",
            name="scale_type",
            field=models.IntegerField(
                choices=[
                    (1, "Integer"),
                    (2, "Balanced"),
                    (3, "Power"),
                    (4, "Ma-Zheng"),
                    (5, "Donegan"),
                ],
                default=1,
            ),
        ),
    ]
