# Generated by Django 4.2.8 on 2026-01-18 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comparisons", "0003_collaborative_features"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comparison",
            unique_together={("project", "user", "index_a", "index_b")},
        ),
    ]
